modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
mixinConfigs="taczmeshloader.mixins.json"

[[mods]]
modId="taczmeshloader"
version="1.0"
displayName="TacZ Mesh Loader"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tacz"
    mandatory=true
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="CLIENT"
